# Generated by Django 5.0.14 on 2026-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherlocation',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
