# Generated by Django 4.2.30 on 2026-05-31 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='Override system OPENAI_API_KEY', max_length=150, null=True)),
                ('model_name', models.CharField(default='gpt-4o', max_length=50)),
                ('system_prompt', models.TextField(default='You are a helpful assistant responding to Telegram inquiries.')),
                ('temperature', models.FloatField(default=0.7)),
                ('is_auto_reply_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_config',
            },
        ),
    ]
