# Generated by Django 4.2.30 on 2026-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='api_base_url',
            field=models.CharField(blank=True, help_text='Override OpenAI API base URL (e.g., for 9router)', max_length=250, null=True),
        ),
    ]
