# Generated by Django 4.2.30 on 2026-05-31 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_chat_id', models.CharField(max_length=150)),
                ('message_text', models.TextField()),
                ('schedule_type', models.CharField(choices=[('once', 'Once'), ('interval', 'Interval'), ('cron', 'Cron')], default='once', max_length=10)),
                ('interval_seconds', models.IntegerField(default=60, help_text="Used if schedule_type is 'interval'")),
                ('cron_expression', models.CharField(blank=True, help_text="Standard crontab format, e.g. '*/5 * * * *'", max_length=100, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='telegram.telegramaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduled_message',
                'ordering': ['next_run_at'],
            },
        ),
    ]
